import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Data sementara (Mock Data) sebelum disambungkan ke Appwrite
const mockData = [
    { id: 1, name: 'Budi Santoso', rt: 'RT 01', jan: 10000, feb: 10000, mar: 10000, apr: 10000 },
    { id: 2, name: 'Siti Aminah', rt: 'RT 03', jan: 10000, feb: 0, mar: 10000, apr: 10000 },
];
export default function DashboardTable() {
    return (_jsxs("div", { className: "bg-white border border-slate-200 rounded-xl shadow-sm mb-6 flex flex-col", children: [_jsxs("div", { className: "p-5 border-b border-slate-200 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4", children: [_jsx("h3", { className: "font-bold text-lg text-slate-800", children: "Rincian Iuran per RT" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { className: "px-4 py-1.5 border border-slate-300 rounded text-sm font-medium text-slate-600 hover:bg-slate-50 transition", children: "Export CSV" }), _jsx("button", { className: "px-4 py-1.5 border border-slate-300 rounded text-sm font-medium text-slate-600 hover:bg-slate-50 transition", children: "Print" })] })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left border-collapse min-w-[800px]", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-200 text-xs text-slate-500 uppercase tracking-wider", children: [_jsx("th", { className: "p-4 font-semibold", children: "Resident Name" }), _jsx("th", { className: "p-4 font-semibold", children: "RT" }), _jsx("th", { className: "p-4 font-semibold text-center", children: "Jan" }), _jsx("th", { className: "p-4 font-semibold text-center", children: "Feb" }), _jsx("th", { className: "p-4 font-semibold text-center", children: "Mar" }), _jsx("th", { className: "p-4 font-semibold text-center", children: "Apr" })] }) }), _jsx("tbody", { className: "text-sm", children: mockData.map((row) => (_jsxs("tr", { className: "border-b border-slate-100 hover:bg-slate-50 transition", children: [_jsx("td", { className: "p-4 font-medium text-slate-800", children: row.name }), _jsx("td", { className: "p-4 text-slate-500", children: row.rt }), _jsx("td", { className: "p-4 text-center", children: row.jan.toLocaleString('id-ID') }), _jsx("td", { className: `p-4 text-center ${row.feb === 0 ? 'text-red-500 font-bold' : ''}`, children: row.feb === 0 ? '0' : row.feb.toLocaleString('id-ID') }), _jsx("td", { className: "p-4 text-center", children: row.mar.toLocaleString('id-ID') }), _jsx("td", { className: "p-4 text-center", children: row.apr.toLocaleString('id-ID') })] }, row.id))) })] }) })] }));
}
